language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# develop 브랜치에 푸시되었을 떄 수행하는 명령어
#프로젝트 내부에 둔 gradelw을 통해 clean & build를 수행한다.
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - shinerani16@gmail.com